### ISSUE TITLE
examples can not run with python 3.6

### ISSUE THREAD

**Issue by MabinogiX** [SUNCAT-Center/catmap#114]
I have run the example in Generating an Input File and I got this error.

Traceback (most recent call last):
  File "D:/Jupyter-notebook/ASE/test.py", line 123, in <module>
    parser.parse()
  File "D:\catmap\catmap\parsers\table_parser.py", line 60, in parse
    self._baseparse()
  File "D:\catmap\catmap\parsers\parser_base.py", line 41, in _baseparse
    self.transition_state_names+self.site_names+tuple(self._gas_sites)):
TypeError: can only concatenate list (not "NoneType") to list

**Comment by gusmaogabriels** [comment]
@Mabinogiysk, are you able to run the example files in your environment with the current CatMAP version?

**Comment by AlexHeustc** [comment]
@Angel-Jia I meet the same problem,have you solved it?

**Comment by AlexHeustc** [comment]
@Angel-Jia I compared the different examples in documentation tutorial and the tutorial in code-master , it seems like the difference bettween the tuple and the list
`rxm.adsorbate_names = ('CO','C','O','H','CH','OH','CH2','CH3')
rxm.transition_state_names = ('C-O','H-OH','H-C')
rxm.gas_names = ('CO_g','H2_g','CH4_g','H2O_g')
rxm.site_names = ('s',)`
