### ISSUE TITLE
mkm_job.py recursive process fail

### ISSUE THREAD

**Issue by reduck96** [SUNCAT-Center/catmap#122]
Hi,

I met another problem like this in tutorial (3-refining_microkinetic_model)
---
[tgmadmin@UOS-YOO 3-refining_microkinetic_model]$ python3 mkm_job.py
Traceback (most recent call last):
  File "mkm_job.py", line 5, in <module>
    model = ReactionModel(setup_file=mkm_file)
  File "/TGM/Apps/PYTHON/3.6.9_for_CatMAP_20190718/lib/python3.6/site-packages/catmap/model.py", line 125, in __init__
    self.load(self.setup_file)
  File "/TGM/Apps/PYTHON/3.6.9_for_CatMAP_20190718/lib/python3.6/site-packages/catmap/model.py", line 384, in load
    exec(compile(open(setup_file, 'r').read(), '<string>', 'exec'), globs, locs)
  File "<string>", line 22, in <module>
  File "/TGM/Apps/PYTHON/3.6.9_for_CatMAP_20190718/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

------
This error-message looks like an error I've seen before. I think it seems to be a problem of reading PKL file.

---
[tgmadmin@UOS-YOO 3-refining_microkinetic_model]$ python3 CO_oxidation.log
Traceback (most recent call last):
  File "CO_oxidation.log", line 22, in <module>
    binary_data = pickle.load(open("CO_oxidation.pkl"))
  File "/TGM/Apps/PYTHON/3.6.9_for_CatMAP_20190718/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
-----

Thank you.
Best regards,
Jinwoo Park 

[3_ref_results.tar.gz](https://github.com/SUNCAT-Center/catmap/files/3451073/3_ref_results.tar.gz)

**Comment by gusmaogabriels** [comment]
Hi @reduck96, 

please check if the problem has been fixed in the latest commit. #123 

Best,
Gabriel
