### ISSUE TITLE
TYPE_ERROR

### ISSUE THREAD

**Issue by Alvarobrt98** [SUNCAT-Center/catmap#135]
When i run the model, i recieve this error:
Traceback (most recent call last):
  File "mkm_job.py", line 3, in <module>
    model = ReactionModel(setup_file=mkm_file)
  File "/home/alvaro/catmap/catmap/model.py", line 124, in __init__
    self.load(self.setup_file)
  File "/home/alvaro/catmap/catmap/model.py", line 422, in load
    self.parse() #Automatically parse in data.
  File "/home/alvaro/catmap/catmap/model.py", line 455, in parse
    self.parser.parse(*args, **kwargs)
  File "/home/alvaro/catmap/catmap/parsers/table_parser.py", line 60, in parse
    self._baseparse()
  File "/home/alvaro/catmap/catmap/parsers/parser_base.py", line 41, in _baseparse
    self.transition_state_names+self.site_names+tuple(self._gas_sites)):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

**Comment by siqiwang55** [comment]
I had the same problem when I tried generating the input file (energies.txt) myself. However if I use the tutorial codes where they generate the input automatically, there is no problem anymore.

**Comment by 755452800** [comment]
If you copy the data from the tutorial and paste it to the energies.txt, you got this problem. The reason is that the copied format is wrong. The space between two items is not strictly a tap (or `\t`) length. By substitute the blanks to a tab (`\t`), all fixed.
